[metadata]
name        = "omnikarai"
version     = "7.1.0"
description = "Omnikarai — native x86-64 compiler, no dependencies (Linux + Windows)"
author      = "Akik Fuad | Fraziym Tech & AI"
license     = "MIT"
homepage    = "https://opi-nine.vercel.app"
repository  = "https://github.com/akikfaraji/OMNIKARAI"

[dependencies]
